### ISSUE TITLE
ADT: issue display

### ISSUE THREAD

**Issue by g-back** [abaplint/abaplint-sci-client#114]
![image](https://user-images.githubusercontent.com/27279305/88042097-ae91d500-cb4b-11ea-9df8-83795f1c4737.png)

Compared to e.g. abapOpenChecks:

![image](https://user-images.githubusercontent.com/27279305/88042198-d7b26580-cb4b-11ea-9fd6-a401690647c9.png)

**Comment by larshp** [comment]
hmm, think I've had the same issue sometime in abapOpenChecks, just don't remember how it was fixed :)

**Comment by g-back** [comment]
Hmm, maybe something to do with scimessage? Maybe we have to add an entry with the hash code for each check into it?

**Comment by larshp** [comment]
yea, also thinking something with `scimessages`

**Comment by g-back** [comment]
For reference, whole PR has discussion about it: https://github.com/larshp/abapOpenChecks/pull/692#issuecomment-487583384

**Comment by g-back** [comment]
Hm, there must be another missing piece in the puzzle.. I've tried adding SCI-messages in the constructor, even random placeholders, but I couldn't get it to display anything in ADT

**Comment by larshp** [comment]
ATC checked, seems okay,
![image](https://user-images.githubusercontent.com/5888506/91963271-ef196c80-ed0d-11ea-8702-114035adde55.png)

**Comment by larshp** [comment]
ADT also seems okay,
![image](https://user-images.githubusercontent.com/5888506/91963568-4cadb900-ed0e-11ea-919d-cc3cc8d2b055.png)
