### ISSUE TITLE
SCI: Can not find special include in dependencies

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint-sci-client#127]
The Include <CNTN01> is part of the dependency repository.
Running AbapLint in docker, no error is reported and the include found.

Running via Code Inspector gives this error:
![image](https://user-images.githubusercontent.com/53995991/91815879-236d2a00-ec35-11ea-98e6-ea30c83fee84.png)

**Comment by larshp** [comment]
first step is fixing https://github.com/abaplint/abaplint/issues/1262, then this might end up as fixed

**Comment by ed-holland** [comment]
SCI got worse after encoding fix.
![image](https://user-images.githubusercontent.com/53995991/91876961-a4501400-ec7d-11ea-9aad-c25c9f809da8.png)

**Comment by larshp** [comment]
https://hub.docker.com/r/abaplint/abaplint-backend/tags?page=1&ordering=last_updated was not updated

looks okay after update of the docker image,

![image](https://user-images.githubusercontent.com/5888506/91885052-69eb7480-ec87-11ea-9720-c5490fb1d50e.png)

![image](https://user-images.githubusercontent.com/5888506/91885116-838cbc00-ec87-11ea-8d33-4d159192cc28.png)

**Comment by ed-holland** [comment]
You are right (docker image must not have updated yet).
Back to the original not-founds
![image](https://user-images.githubusercontent.com/53995991/91937361-064a6100-ecf2-11ea-9aba-b94a565dd418.png)

Can the version be shown like the variant? See #40.

**Comment by larshp** [comment]
currently not finding the dependencies in this example,

![image](https://user-images.githubusercontent.com/5888506/91941778-0baba980-ecfa-11ea-81af-40bd577d5c28.png)

**Comment by larshp** [comment]
https://github.com/abaplint/abaplint-sci-client/pull/130

**Comment by ed-holland** [comment]
Tested pull request #139.

![image](https://user-images.githubusercontent.com/53995991/92204634-34f84100-ee84-11ea-9c2f-250c8482b6a8.png).
The message states "ABAP" as the program so that linking is not possible. 

The messages are probably caused by macro's. I'll check and adjust the config and retest.

**Comment by ed-holland** [comment]
Most of the above errors are from this code in `<contro>`:
![image](https://user-images.githubusercontent.com/53995991/92207623-d03fe500-ee89-11ea-8fe0-88383dda9f70.png)


the TYPEEND issue is caused by this construct in include SBALTYPE. 
![image](https://user-images.githubusercontent.com/53995991/92207161-134d8880-ee89-11ea-83e0-b8090bb05435.png)

The macro's used are added to globalMacros.

The special includes seem to work fine. Thx
Should i create new issues for the above two?

**Comment by larshp** [comment]
no, I'm no it 👍

**Comment by larshp** [comment]
https://github.com/abaplint/abaplint/pull/1271/commits/ec133034ea3448474e57bcca86b74552bfdc39e5

**Comment by larshp** [comment]
2.41.1 published

**Comment by ed-holland** [comment]
issues are gone. Thanks.
