### ISSUE TITLE
Option "Continue into SAP" does not work with classes/exceptions

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint-sci-client#129]
Find_clas_dependencies (https://github.com/abaplint/abaplint-sci-client/blob/master/src/deps/zcl_abaplint_deps_find.clas.abap#L469) does not check if a class is an SAP object (like https://github.com/abaplint/abaplint-sci-client/blob/master/src/deps/zcl_abaplint_deps_find.clas.abap#L729). Therefore, the dependencies search will go deeper into SAP classes often leading to "max depth reached" error.

This is especially the case with exception classes that inherit from SAP exception classes. So you get max depth in CX_STATIC_CHECK, CX_DYNAMIC_CHECK, or CX_ROOT.

**Comment by larshp** [comment]
`CX_ROOT` contains stuff that is usually used in exception classes, ie. its needed in order to do a correct syntax check

have you tried increasing the depth?

**Comment by mbtools** [comment]
increased depth removes the error. but it's getting a bit slow. i will do some tracing to see what can be optimized.
