### ISSUE TITLE
Dependency Generator: Existing file is not overwritten if it is changed

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint-sci-client#142]
If an existing member in the dependency repository is changed (due to forms reduction or special macro correction), the member is not overwritten.

Also logging does not show correct results. After deleting two members (ifre_begin_of_re_ea_fin.prog.abap and ifre_end_of_re_ea_fin.prog.abap) it reported:
```
Add /src/fvvi/ ifre_begin_of_re_classic.prog.abap
Add /src/fvvi/ ifre_begin_of_re_classic.prog.xml
Add /src/fvvi/ ifre_begin_of_re_ea_fin.prog.xml
Add /src/fvvi/ ifre_end_of_re_classic.prog.abap
Add /src/fvvi/ ifre_end_of_re_classic.prog.xml
Add /src/fvvi/ ifre_end_of_re_ea_fin.prog.xml
```
Not showing the deleted members.

**Comment by larshp** [comment]
report https://github.com/abaplint/abaplint-sci-client/blob/master/src/zabaplint_dependencies.prog.abap

class https://github.com/abaplint/abaplint-sci-client/blob/master/src/deps/zcl_abaplint_deps_git.clas.abap

**Comment by ed-holland** [comment]
related #144

**Comment by ed-holland** [comment]
Closing as original issues is solved.
