### ISSUE TITLE
Dependency Generator: SHA between local and remote are always different

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint-sci-client#144]
The Dependencies generated always show up as changed due to different SHA1 field

Environment: 
- Gitlab on Linux
- SAP on Windows

![image](https://user-images.githubusercontent.com/53995991/92321504-dd480a00-f02a-11ea-98a0-94c39daa5447.png)

**Comment by ed-holland** [comment]
Debug Details:
![image](https://user-images.githubusercontent.com/53995991/92321768-e934cb80-f02c-11ea-9c63-46d8f8aa1f23.png)
Data Details (same):
![image](https://user-images.githubusercontent.com/53995991/92321791-28631c80-f02d-11ea-996c-4dd033454565.png)

**Comment by larshp** [comment]
Program name = ZABAPLINT_DEPENDENCIES ?

**Comment by larshp** [comment]
issue reproduced

**Comment by ed-holland** [comment]
Yes, that is the program used.

**Comment by larshp** [comment]
issue: after serialization, the file content is changed, but the SHA1 is not recalculated

**Comment by larshp** [comment]
fix added to PR https://github.com/abaplint/abaplint-sci-client/pull/218

**Comment by ed-holland** [comment]
Tested PR. Issue is gone. Thx.
