### ISSUE TITLE
user exit style enhancements for "METHOD handle_special_abaps."

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint-sci-client#147]
https://github.com/abaplint/abaplint-sci-client/blob/master/src/deps/zcl_abaplint_deps_serializer.clas.abap#L258

**Comment by ed-holland** [comment]
Example Implementation:
![image](https://user-images.githubusercontent.com/53995991/92386920-fa590780-f114-11ea-93ad-248bd7a4a5f8.png)

**Comment by ed-holland** [comment]
PR #148
