### ISSUE TITLE
Environment Object Type XB can not be converted to Transport Object Type

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint-sci-client#150]
Dependency determination created an abend as this type could not be translated.
Object causing the issue was `FUGR FACI`.

**Comment by mbtools** [comment]
Thought I had fixed this in https://github.com/abaplint/abaplint-sci-client/pull/124. 

https://github.com/abaplint/abaplint-sci-client/blob/master/src/deps/zcl_abaplint_deps_find.clas.abap#L289

Is this where is dumps?

**Comment by ed-holland** [comment]
It dumped already on the line before. The Type XB did not convert.
Also the fuba call on around 300 did not get the correct input and always failed.
See #151

**Comment by ed-holland** [comment]
Merged
