### ISSUE TITLE
Generated FUGR are not ignored in SCI - add TOBJ dependencies

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint-sci-client#155]
Example:
![image](https://user-images.githubusercontent.com/53995991/92748687-ab65d900-f385-11ea-8e5d-09453d6fbf18.png)

SCI Issue:
![image](https://user-images.githubusercontent.com/53995991/92748745-bd477c00-f385-11ea-87c9-2ffa57127d80.png)

AbapLint in Docker excludes these errors.

**Comment by mbtools** [comment]
exclude list in screenshot is missing `"#jcs#lfcc_actions..."` (you have ... lfpa...)

**Comment by ed-holland** [comment]
you are correct. I must be getting blind... both lfpa and lfcc variations exist. That raises the question why AbapLint command does not have an issue with it.

**Comment by ed-holland** [comment]
I've redone the exceptions and changed them to global exceptions. AbapLint cli is giving no issues.
SCI is giving issues.. Interestingly enough, all issues are from Table Maintenance Views.

Could it be that the generated function groups are not skipped (`"skipGeneratedFunctionGroups": true,`)?

**Comment by mbtools** [comment]
i've had similar issue with generated fugr https://github.com/abaplint/abaplint/issues/1300. it's looking for `TOBJ` with same name as the `FUGR`. I think we need to add the `TOBJ` to deps

**Comment by larshp** [comment]
> i've had similar issue with generated fugr [abaplint/abaplint#1300](https://github.com/abaplint/abaplint/issues/1300). it's looking for `TOBJ` with same name as the `FUGR`. I think we need to add the `TOBJ` to deps

yea, this also hit me, think this is the problem, the TOBJ object is not found as a dependency, so abaplint cannot know it is generated

**Comment by mbtools** [comment]
unless you are SAP, linting the generated FUGR makes no sense. It's pointless to find and serialize deps of these FUGR, send to server, and then find out that the object is excluded in 99.9% of the cases. I think we should exclude them completely from SCI no matter the abaplint setting.

**Comment by larshp** [comment]
transparency

perhaps you are SAP, perhaps the user only runs rule check_syntax, perhaps the user gets the errors when running on command line so I'd expect the same errors to show up when running SCI

**Comment by larshp** [comment]
I'm starting this now
