### ISSUE TITLE
SCI - message_exists: Message class with name space not found

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint-sci-client#157]
Issue:
![image](https://user-images.githubusercontent.com/53995991/92749477-7017da00-f386-11ea-8fdd-0c9860aebd5c.png)

AbapLint Docker does not show this error.

**Comment by larshp** [comment]
is the message class part of the dependencies sent to the abaplint server?

**Comment by ed-holland** [comment]
Can you point me to where this can be shown.
The Docker Log shows only a single entry without details.

**Comment by larshp** [comment]
as a first step try running https://github.com/abaplint/abaplint-sci-client/blob/master/src/zabaplint_list_deps.prog.abap for the object being checked, with parameters matching the sci settings

**Comment by ed-holland** [comment]
As the AbapLint Docker image which uses the Dependency repository created using this toolset has no problem means that the dependency is created correctly. If it is send to the SCI server is unclear.
I have to assume it is not.

Can one switch on a verbose mode for the SCI-Server?

**Comment by mbtools** [comment]
I use `MESSAGE s003(/mbtools/bc).` and the message class is found by `ZABAPLINT_LIST_DEPS`. Is your message class defined in `REPORT`, `CLASS`, or `FUNCTION-POOL`?

**Comment by ed-holland** [comment]
Used the new DEBUG report.  It fails with an Exception during cl_gui_frontend_services=>file_save_dialog SY-SUBRC=4. No popup is shown.

It fails because there is no default filename.

**Comment by larshp** [comment]
hmm, think I used the same as in abapGit, anyhow, pull requests welcome

**Comment by ed-holland** [comment]
looks like it is the namespace causing the problem in the filename.

`abaplint-sci-client-data-PROG-/JCS/BC_BDC_DELETE.zip`

**Comment by larshp** [comment]
yea, I forgot about that, just replace the "/" with anything, its the contents inside the zip that matters

**Comment by ed-holland** [comment]
The downloaded ZIP file does not contain the message class in its deps folder

**Comment by ed-holland** [comment]
> I use `MESSAGE s003(/mbtools/bc).` and the message class is found by `ZABAPLINT_LIST_DEPS`. Is your message class defined in `REPORT`, `CLASS`, or `FUNCTION-POOL`?

It is indeed found in DEPS but not when you try to check it via Code Inspector.

**Comment by larshp** [comment]
are you using the same settings in SCI and ZABAPLINT_LIST_DEPS ? It calls the same logic, so

**Comment by ed-holland** [comment]
one2one copy from json to sci.

**Comment by ed-holland** [comment]
Did a compare between ZABAPLINT_LIST_DEPS and ZABAPLINT_DEBUG and both do not see the msag. It is defined in the report statement. 

![image](https://user-images.githubusercontent.com/53995991/93301168-577d4900-f7f8-11ea-959e-17e2c61f52c3.png)

FUBA REPOSITORY_ENVIRONMENT_SET does not detect it in the header. It does detect MESS/MSAG objects when they are used explicitely.

To be honnest, the `MESSAGE-ID` specification in this abap is not used.

I've tested it with a defined message and it was detected.

The question now is if this should be fixed or not. From my point, removing the definition in the source resolved it.

**Comment by ed-holland** [comment]
Closing as there seems to be no need to implement more.
