### ISSUE TITLE
SCI - Check_Include: Special Includes not found

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint-sci-client#159]
Issue:
![image](https://user-images.githubusercontent.com/53995991/92926918-10c8d100-f43d-11ea-9039-bf1b27b07b61.png)

The special includes which are found by Dependency Generator are not found by SCI.

**Comment by larshp** [comment]
is the object part of the dependencies sent to the abaplint server?

**Comment by ed-holland** [comment]
Using the new Debug program, the related objects where added to a zip.

It does not contain the <cntn01> program in deps/swc.

![image](https://user-images.githubusercontent.com/53995991/93108443-14fe2400-f6b3-11ea-9be5-3a058329f8d5.png)

**Comment by mbtools** [comment]
Isn't that why you did https://github.com/abaplint/abaplint-sci-client/pull/115?

**Comment by ed-holland** [comment]
initially yes. Then they showed up in the dependency list by automatically. I had thought that they showed up because i had run the  Abap SAPRSEUB. This is not the case (or 740 SP24 blocked it again).

Anyway, the include is still part of the dependency repository.
![image](https://user-images.githubusercontent.com/53995991/93661913-e63dd000-fa5b-11ea-95b2-af6b5f8de3b3.png).

The deps generated using the new Debug program does not contain the special includes.

Can SCI use the Deps repository directly? That would speed up SCI a lot i think (it is awfully slow currrently).
If not, the special ones need to be added somehow to SCI?

Currently i have 3 special includes in my dependency list:
![image](https://user-images.githubusercontent.com/53995991/93662003-ad522b00-fa5c-11ea-8d10-c7daec20b929.png)

**Comment by ed-holland** [comment]
As long as SCI does not use the Deps repository, these special includes needs to be added in the configuration or exit.

**Comment by ed-holland** [comment]
PR #214 resolves issue

**Comment by ed-holland** [comment]
Closing. Issue Resolved. Thx
