### ISSUE TITLE
SCI - parser_error: Macro's are not recognized

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint-sci-client#160]
Issue:
![image](https://user-images.githubusercontent.com/53995991/92927110-643b1f00-f43d-11ea-91f7-7d93d0773cda.png)

AbapLint parses macro's nicely. SCI does not recognize them.

**Comment by larshp** [comment]
is the object containing the macro part of the dependencies sent to the abaplint server?

**Comment by larshp** [comment]
try running https://github.com/abaplint/abaplint-sci-client/blob/master/src/zabaplint_debug.prog.abap to download the zip for the object, unzip to local folder and try running `abaplint` command line tool locally

**Comment by ed-holland** [comment]
Results from local run:
![image](https://user-images.githubusercontent.com/53995991/93764767-fdbfb900-fc13-11ea-888f-c322af4e5867.png)

**Comment by larshp** [comment]
so it looks like command line and sci gives the same results?

**Comment by ed-holland** [comment]
When i run AbapLint cli for the whole package, these issues do not show up.

Looks like this is caused by the first error though (as it contains the macros)... issue #159.
When it is resolved, the macro's will probably be found.

**Comment by larshp** [comment]
okay, so this is a function group, then we can try merging https://github.com/abaplint/abaplint-sci-client/pull/139

**Comment by ed-holland** [comment]
Closing. Issue is not showing up anymore.
