### ISSUE TITLE
SCI - unknown_types: Lookup Table with includes / non-existing includes

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint-sci-client#168]
3 issues of this type.
![image](https://user-images.githubusercontent.com/53995991/93263630-54596d00-f7a6-11ea-9c9e-ca91664dd560.png)

pa0001 & pa0003 & imak are transparent tables with includes containing non-existing includes.

**Comment by mbtools** [comment]
If the include does not exist, there is no entry in `ddtypes`. With #165 these includes are ignored which I would say is correct.
https://github.com/abaplint/abaplint-sci-client/pull/165/files#diff-2786c6dbf641ebb85d78a96bc9a45486R725 

how would abaplint know that it's ok for the include not to exist?

**Comment by ed-holland** [comment]
Some more details...
PA0001 type TABL, It contains the include PAKEY, PSHD1, PS0001 (all type TABL and exist in DDTYPES).
The include PS0001 contains the includes PS0001_SAP (type TABL) and include CI_P0001 which does not exist in DDTYPES.

![image](https://user-images.githubusercontent.com/53995991/93299088-c5277600-f7f4-11ea-807b-01ffb7dc9b47.png)

I'm assuming that the error is coming from CI_P0001 and it is correct that the type is unknown.
AbapLint command line does not have the issue with it. 
Can the field/type be shown that is causing the issue like in AbapLint?

I've checked all the ddic related tables and could not find this include. The only difference to a non-existing table is that it is defined in an existing table. 

I've compared the findings with the other two tables and both have CI_* includes that do not exist.
From what i read they are for customer fields to be included (most likely from the time before append structures existed).

**Comment by mbtools** [comment]
The msg comes from abaplint. @larshp can we return the name of the component here?
https://github.com/abaplint/abaplint/blob/master/packages/core/src/rules/unknown_types.ts#L79

Or we add a dummy dependency for structures that don't exist in DDTYPES like "type string".

**Comment by larshp** [comment]
the CI_ includes should now work without giving errors

**Comment by ed-holland** [comment]
Issue is fixed. Thanks
