### ISSUE TITLE
How does the Dependency Depth work ?

### ISSUE THREAD

**Issue by sbcgua** [abaplint/abaplint-sci-client#169]
There is this new param at configuration "Dependency depth". What does it mean and how does it work ?

After update I either face "Max depth reached" error, or the check hangs forever ... would be very nice to add some doc

**Comment by mbtools** [comment]
https://github.com/abaplint/abaplint-sci-client/blob/master/docs/installation.md#initial-setup OK?

**Comment by sbcgua** [comment]
Yeap, thanks ! Docs are very valuable :) :+1:

P.S. "Max depth reached" error is probably subject for a separate issue
