### ISSUE TITLE
Type-pools

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint-sci-client#171]
* TYPE are not handled properly in abaplint right now, so skip
https://github.com/abaplint/abaplint-sci-client/blob/main/src/deps/zcl_abaplint_deps_find.clas.abap#L1031-L1033

Is that still the case? What needs to get done to make it work?

**Comment by larshp** [comment]
it is still the case

just need time to implement it, https://github.com/abaplint/abaplint/issues/1148
