### ISSUE TITLE
SCI: Tool to run code-inspector for specific Objects

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint-sci-client#172]
Provide Tool to run Code Inspector for specific Objects
- Sub Package only
- Specific Objects
- Transport Request

**Comment by mbtools** [comment]
SE80 > Right-click on object > Check > ATC with ... <your abaplint variant> ?

**Comment by ed-holland** [comment]
Beside debugging, the most use for me is to run it for a transport request. Running it from within AG takes 45 minutes for our main package.

**Comment by mbtools** [comment]
I noticed drop in perf too. I need to do some traces but caching the serialized deps should help. Same with getting the environment. There’s just too much repetition

**Comment by ed-holland** [comment]
Forgot to state, the transport request objects are converted to main objects automatically like AG would do.

**Comment by mbtools** [comment]
SE80 does it for transports, too, and it looks like it collects the main objects. 

![image](https://user-images.githubusercontent.com/59966492/93689106-51f25e00-fa99-11ea-962e-7db2cd366d3d.png)

Anyway, a standalone prg would be nice too

**Comment by ed-holland** [comment]
Indeed. Was not aware of that one.

The plan is to run SCI from inside the TMS exit "Before Export".
Or is there a direct way to force this via SAP configs?

**Comment by larshp** [comment]
in transaction ATC, but you have a lot more control if implementing the exit, 

![image](https://user-images.githubusercontent.com/5888506/93706159-d8ec1880-fb23-11ea-8ef2-c7ba87d97f49.png)
![image](https://user-images.githubusercontent.com/5888506/93706162-dd183600-fb23-11ea-89be-3c3bc25073c9.png)

**Comment by ed-holland** [comment]
Thx, i will check it out before creating the exit. It might be sufficient for the beginning.

**Comment by ed-holland** [comment]
Merged
