### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint-sci-client#182]
Ideas:
- Client-side memory caching of dependencies and serialized objects (see #181, should work)
- Client-side disk-based caching of dependencies and serialized objects (see #181, needs attention to details)
- Determine dependencies once for all objects and send to server once (in RUN_BEGIN)
- Server-side caching of dependencies

**Comment by larshp** [comment]
caching is always difficult, just not sure if there is any way around it

**Comment by sbcgua** [comment]
some thoughts on the complete client-server caching flow: https://github.com/abaplint/abaplint-sci-client/pull/181#issuecomment-696623120

**Comment by mbtools** [comment]
Done with #199
