### ISSUE TITLE
Use class CL_HTTP_UTILITY ?

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint-sci-client#206]
can somebody help checking if CL_HTTP_UTILITY is available in 702? for base64 decoding

`./src/zcl_abaplint_backend.clas.abap[111, 19] - Recommendation: Replace Function SSFC_BASE64_ENCODE with: use class CL_HTTP_UTILITY methods (function_module_recommendations) [E]`

**Comment by mbtools** [comment]
7.02 SP 21:

![image](https://user-images.githubusercontent.com/59966492/95865815-14e65800-0d35-11eb-91f6-7501c6ecfc53.png)

DE/ENCODE_BASE64: string in, string out
DECODE_X_BASE64: string in, xstring out
ENCODE_X_BASE64: xstring in, string out
