### ISSUE TITLE
Table/Structure SI_FKKOPR does not contain any components

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint-sci-client#219]
I forgot about this issue

see https://github.com/abapGit/abapGit/pull/4034 and https://github.com/abaplint/abaplint/issues/1444

Suggest that `abaplint-sci-client` add a dummy field in the XML after serialization

I'd like to keep SCI logic outside of abapGit, plus its a valid error message from abaplint, since its not possible to create a structure/table with no fields

**Comment by ed-holland** [comment]
Dummy Field is also a valid solution.

**Comment by mbtools** [comment]
+1 for dummy 

Some background: The SI and CI includes are delivered by SAP ("SAP/Customer include") as part of software components. I could not find any association with switches. An example is table T005, which has include SI_T005ABA shipped as part of SAP_ABA and SI_T005HR which is empty unless you have HR installed.

**Comment by larshp** [comment]
I'm starting this now

**Comment by ed-holland** [comment]
Issue resolved. Thanks.
