### ISSUE TITLE
API request failed [500]: unsupported charset "ISO-8859-1"

### ISSUE THREAD

**Issue by BlackmanCC** [abaplint/abaplint-sci-client#231]
When I run the sci check againt abaplint backend. I get the error:

API request failed [500]: unsupported charset "ISO-8859-1"

Our System is an 740 non-unicode system. 

Do you have ideas how I can fix this?

**Comment by larshp** [comment]
see https://github.com/abaplint/abaplint-sci-client/pull/232

**Comment by BlackmanCC** [comment]
will try it out thanks a lot

**Comment by BlackmanCC** [comment]
seems to work now.
It get LINT_* errorcodes now. 

Thank you very much!

**Comment by larshp** [comment]
fixed, closing
