### ISSUE TITLE
 Loop, not a table type, * not found,

### ISSUE THREAD

**Issue by BlackmanCC** [abaplint/abaplint-sci-client#233]
I am getting LINT_0017 and LINT_0018 errormessages, that table type is not found. 
Corresponding table types are defined in data dictionary.

**Comment by larshp** [comment]
yea, so this depends a lot on the `errorNamespace` in the configuration, plus the options for dependencies configured in configured in `ZABAPLINT_CONFIG`

**Comment by BlackmanCC** [comment]
```
LINT_0108
 Type of "gt_pathitems" contains unknown: Table Type, unknown
````
table type gt_pathitems in example is ZSWAGFWPATHITEMS_TAB

config is:

```
  "syntax": {
    "version": "v702",
    "errorNamespace": "^(Z|Y|LT?CL_|TY_|LIF_|.*SWAGFW)",
```

**Comment by BlackmanCC** [comment]
@larshp dependency depth is 12 
what else can I check?

**Comment by larshp** [comment]
Reports ZABAPLINT_LIST_DEPS and ZABAPLINT_DEBUG can be used for debugging

first report will show which objects are found and sent to the server, second report will reproduce the files sent to the server and save to a local zip for debugging purposes
