### ISSUE TITLE
SCI results don't point to program includes

### ISSUE THREAD

**Issue by neptune3221** [abaplint/abaplint-sci-client#234]
When viewing the abaplint results in SCI, the results seem to only point to the base program rather than include where the error actually lies.

![abaplintResults](https://user-images.githubusercontent.com/3679929/104460347-feda7480-557b-11eb-96f5-17eb5957f749.PNG)

Contrast this with running Openchecks on the same single program, which correctly lists the include and takes the user directly to that file on double click.

![OpenchecksResults](https://user-images.githubusercontent.com/3679929/104460547-3b0dd500-557c-11eb-8196-0aea3cea1592.PNG)

**Comment by larshp** [comment]
thanks, I have reproduced the problem,

![image](https://user-images.githubusercontent.com/5888506/104463851-92c73300-55b2-11eb-8f63-de700b5eaeae.png)

![image](https://user-images.githubusercontent.com/5888506/104463899-9e1a5e80-55b2-11eb-82dc-8d1b0f4ea403.png)

**Comment by larshp** [comment]
@neptune3221 try again, latest version of the abap code from this repository

**Comment by neptune3221** [comment]
Confirmed fix! everything looking good here now. Thanks @larshp
