### ISSUE TITLE
Replace ajson with abapgit_ajson

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint-sci-client#247]
abapGit now contains the complete ajson code. A separate installation of `zcl_ajson...` should not be required anymore. Instead the sci client should use `zcl_abapgit_ajson...`.

**Comment by larshp** [comment]
yea...

![image](https://user-images.githubusercontent.com/5888506/115673368-d917f500-a34c-11eb-8a50-ea1ac46a5541.png)

**Comment by larshp** [comment]
I'm starting this now
