### ISSUE TITLE
Certificate Error

### ISSUE THREAD

**Issue by Fmueller17** [abaplint/abaplint-sci-client#261]
Hello,
I tried to install the SCI Client and want to use the https://sci.abaplint.app for the linting.

I downloaded the root certificate from the web site and installed it in strust.

But there is also a Kubernetes Ingress Controller Fake Certificate. I tried to create it from the ICM Trace but then I get a certificate mismatch. Where can I download it?

![grafik](https://user-images.githubusercontent.com/59128840/140728385-6553c3c0-7dd1-47e2-b5e5-fa97406bedf4.png)

![grafik](https://user-images.githubusercontent.com/59128840/140728605-7f8aaa30-17dd-4c6f-b5f0-82ee43c21146.png)

**Comment by larshp** [comment]
did you download the certificate?

![image](https://user-images.githubusercontent.com/5888506/140733633-06df241b-06c0-4d14-a892-256a79dbba70.png)

there is nothing as such wrong with the certificate, see https://www.ssllabs.com/ssltest/analyze.html?d=sci.abaplint.app
![image](https://user-images.githubusercontent.com/5888506/140733512-0557bd0b-9742-45c1-ade3-6ad09911f229.png)

**Comment by Fmueller17** [comment]
@larshp  I have troubles with this one. Maybe because it is not trusted.

<img width="1009" alt="grafik" src="https://user-images.githubusercontent.com/59128840/140737317-e24899c4-bdcb-40f2-a382-153dd1031723.png">

**Comment by Fmueller17** [comment]
@larshp I downloaded it now from this website and add it to strust, but still the same error.
![grafik](https://user-images.githubusercontent.com/59128840/140738229-b7062163-4be8-40be-a8c2-a18f7e0f613c.png)

![grafik](https://user-images.githubusercontent.com/59128840/140738343-b3c7dc12-495e-4adf-b301-a58c7d571a9b.png)

**Comment by mbtools** [comment]
Looks like the fake cert is gone. It works for me with the regular Let's Encrypt intermediate and root certs.

**Comment by Fmueller17** [comment]
Sorry for the late reply. I had to install my new computer first. No it works for me to.

**Comment by larshp** [comment]
can the issue be closed?

**Comment by Fmueller17** [comment]
Yes.
