### ISSUE TITLE
SAP Dependency code generation fails with DUPKEY

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint-sci-client#263]
![image](https://user-images.githubusercontent.com/53995991/142999675-d858a5b0-dd92-4906-a181-f0053e9157e1.png)

The dependency code generation using ZABAPLINT_DEPENDENCIES fails with
![image](https://user-images.githubusercontent.com/53995991/142998315-99658239-147d-45ef-a10e-d1a580b0fd98.png)

Dump:
![image](https://user-images.githubusercontent.com/53995991/142998528-9dee215e-869c-4389-b456-18fdf3728b0f.png)
[dump.txt](https://github.com/abaplint/abaplint/files/7586894/dump.txt)

**Comment by larshp** [comment]
issue moved to abaplint-sci-client from abaplint

**Comment by ed-holland** [comment]
Debugging revealed that it is caused by the function module RK_AL_SEQ_DELETE.
This function module is active but does not have any active code.
![image](https://user-images.githubusercontent.com/53995991/143213814-787192ea-e042-4aaa-82d8-47135826ad41.png)

Using ZABAPLINT_LIST_DEPS the function group was serialized. It fails at the same spot.

The Log also raised some errors:
![image](https://user-images.githubusercontent.com/53995991/143214168-41a50ed8-921a-431d-beac-69220b801440.png)

**Comment by ed-holland** [comment]
I need to refraise... there is indeed a function module with the same name but in lower case. Not sure how SAP did this...

![image](https://user-images.githubusercontent.com/53995991/143214584-09c24bf7-ae95-439a-ba1e-af627aedbdd5.png)

![image](https://user-images.githubusercontent.com/53995991/143214763-ce907666-aa9a-4085-93be-476d0349d985.png)

**Comment by ed-holland** [comment]
I've deleted the function module with lowercase name and now the issue is resolved.
