### ISSUE TITLE
Check variant maintenance gets stuck

### ISSUE THREAD

**Issue by fabianlupa** [abaplint/abaplint-sci-client#268]
https://github.com/abaplint/abaplint-sci-client/blob/4ea4188f87bcc6a5f4dd2dc2c6d614c76a08fea2/src/zcl_abaplint_check.clas.abap#L126

Would it be possible to remove / move this call? For some time we couldn't edit any check variants because after selecting it and pressing edit you would get a loading indicator and nothing would happen. There also isn't a process in SM50. After some debugging I noticed that it's the abaplint check that is responsible. The call above causes a network call which apparently get's stuck for some reason in our setup (but doesn't time out either anytime soon). We aren't actively using this check just have it installed. You also cannot deactivate the check to fix this temporarily as the option in the menu where you enable and disable checks cannot be opened either. I assume both screens cause the class constructor to be called for every check class including this one.

**Comment by larshp** [comment]
stupid `class_constructor`, move the logic out of the class constructor instead, call it when its needed
