### ISSUE TITLE
Dependencies do not seem to be considered

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint-sci-client#27]
the abaplint/dependencies project has dependencies defined. 

Code Inspector messages:
![image](https://user-images.githubusercontent.com/53995991/84658698-8ee90a80-af16-11ea-8513-4438fb36ce9c.png)

AbapLint config:
![image](https://user-images.githubusercontent.com/53995991/84658765-ade79c80-af16-11ea-890d-d21817931507.png)

The GitHub workflow did not have this issue. Does the Docker-Image require changes for this?

**Comment by larshp** [comment]
Inside the ABAP system it will take the dependencies from the system itself, using the dependency depth setting:

![image](https://user-images.githubusercontent.com/5888506/84659186-4da52a80-af17-11ea-98a6-d401c4b6a4dc.png)

**Comment by ed-holland** [comment]
Is there a big performance impact when one chooses depth=10 or would 2 be sufficient?

**Comment by larshp** [comment]
try :)

the dependency graph in ABAP is quite messed up, everything uses everything

need to add more logic into this repo so it does not find as much

**Comment by larshp** [comment]
or, it might be nice to have a setting in the configuration, to choose to use dependencies from git or from the system itself

**Comment by larshp** [comment]
its probably also a problem wrt versioning, if the software is developed on 750, targeted for 702, and some of the dependencies inside the system is with 750 syntax

however, using dependencies from git also causes problems with authentication

**Comment by ed-holland** [comment]
At depth=2 the errors are still there and there is a message
![image](https://user-images.githubusercontent.com/53995991/84667386-90203480-af22-11ea-89dc-3f42e3399da3.png)

At depth=3 it fails on assert
![image](https://user-images.githubusercontent.com/53995991/84667709-00c75100-af23-11ea-93e2-662e919c224a.png)

**Comment by larshp** [comment]
check value of `ls_files_item-item`, and see if its supported by abapGit

**Comment by ed-holland** [comment]
![image](https://user-images.githubusercontent.com/53995991/84674476-3ff9a000-af2b-11ea-9145-87fcbf4d5836.png)

Can it be adopted to change the exception into a warning/error for not-supported type?

**Comment by ed-holland** [comment]
> however, using dependencies from git also causes problems with authentication

I'm using access tokens in the URL which resolves the auth issues. 
One has to consider though that they are visible to every body.

**Comment by larshp** [comment]
adopted: yea, probably just skip object types that are not supported by abapGit

**Comment by ed-holland** [comment]
closing as many changes have been made to linter/dependency determination.
