### ISSUE TITLE
Syntax error in program "ZCL_ABAPLINT_BACKEND

### ISSUE THREAD

**Issue by preinboth** [abaplint/abaplint-sci-client#285]
Error analysis
    The following syntax error has occurred in program
     ZCL_ABAPLINT_BACKEND==========CP        :
    Type "TY_SERIALIZATION" is unknown.

    " "
![10-09-_2023_16-55-49](https://github.com/abaplint/abaplint-sci-client/assets/6295832/74ea8ce4-65e9-4139-8995-0593cf52b106)

**Comment by larshp** [comment]
yea, it broke with one of the recent abapGit changes

**Comment by larshp** [comment]
@preinboth try again, https://github.com/abaplint/abaplint-sci-client/pull/286 merged

**Comment by preinboth** [comment]
@larshp  thx
