### ISSUE TITLE
Circular reference between objects yields in objects being skipped by abaplint

### ISSUE THREAD

**Issue by fdupret** [abaplint/abaplint-sci-client#295]
I'm not sure if this should be fixed upstream or here.

Context: two objects refer to each other (example: header class to item class and item class to header class).
Issue: these two objects are not checked by abaplint because the object is seen as a dependency for itself.

Example:
[Uploading abaplint-sci-client-data-CLAS-ZCL_TEST_HEADER.zip…]()

This test should fail with a parser error for 7.02 but it yields 0 issues.
When removing the circular reference, the parser error issue is correctly detected by abaplint.

**Comment by fdupret** [comment]
Suggested solution: 
remove self from MT_RESULTS before this: https://github.com/abaplint/abaplint-sci-client/blob/bb7a24d14a409ef67b988fbc52e480ca23256885/src/deps/zcl_abaplint_deps_find.clas.abap#L466-L471

**Comment by larshp** [comment]
thanks, pull requests welcome
