### ISSUE TITLE
zabaplint_dependencies: Function table parameter references are not selected for dependency repository

### ISSUE THREAD

**Issue by PabloMalerbaRedwood** [abaplint/abaplint-sci-client#297]
Version:
abapGit version: 1.127.0
XML version: v1.0.0
GUI version: 8000.01.01
APACK version: 1
LCL_TIME: 1709742310 +0000
SY time: 20240306 172510 3600
SY release: 740 SP 0029

The Tables used in function parameters are not added to the dependency list.
<img width="420" alt="image" src="https://github.com/abaplint/abaplint-sci-client/assets/159277426/7905e76e-3dcb-41fc-97f0-b44e7d0fcce2">

This then causes Linter errors like this
./src/ecc/#jcs#fi.fugr.#jcs#fi_ff67_preparation.abap[121, 3]                  - "t012" not found, Target (check_syntax) [E]

**Comment by mbtools** [comment]
Duplicate
