### ISSUE TITLE
SAP Includes not recognized in FUGR TOP include file

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint-sci-client#302]
Our function group Top Include contains two further includes importing definitions from SAP.
These are not seen. 

![image](https://github.com/user-attachments/assets/ef42db29-22ae-4eb1-8534-c6664452666a)

Issues shown during linter
```
./src/ecc/ext/#jcs#ma.fugr.#jcs#lmaf01.abap[27, 3]                           - "gc_fkkaktiv2_status_stopped" not found, findTop (check_syntax) [E]
./src/ecc/ext/#jcs#ma.fugr.#jcs#lmaf01.abap[104, 5]                          - "gc_mad_dispatcher" not found, findTop (check_syntax) [E]
./src/ecc/ext/#jcs#ma.fugr.#jcs#lmaf01.abap[145, 3]                          - "gc_fkkaktiv2_status_stopped" not found, findTop (check_syntax) [E]
./src/ecc/ext/#jcs#ma.fugr.#jcs#lmaf01.abap[213, 3]                          - "gc_appl_log_event_17[96](https://vdocker.sap.internal:8929/abap/abap-fca/-/jobs/218921#L96)" not found, findTop (check_syntax) [E]
./src/ecc/ext/#jcs#ma.fugr.#jcs#ma_prepare.abap[113, 5]                      - "gc_mem_id_aktyp" not found, findTop (check_syntax) [E]
./src/ecc/ext/#jcs#ma.fugr.#jcs#ma_prepare.abap[147, 5]                      - "gc_mad_dispatcher" not found, findTop (check_syntax) [E]
```

Verification of dependency repository confirmed that the FKKB package did not include these includes.

Test also performed using ZABAPLINT_LIST_DEPS.

**Comment by larshp** [comment]
two options:
a: add the includes to the dependencies repository
b: add the constants to `globalConstants` in the configuration

**Comment by ed-holland** [comment]
Just noticed that we have LFKKAKTIV2CON already added in the deps generation.
![image](https://github.com/user-attachments/assets/012798c9-d205-42c0-bb77-f19e30fc136b)

will investigate why it is not being included (probably because it is an include).

**Comment by larshp** [comment]
> both would be workarounds. Should i look for a more permanent sollution in Abap?

I think SAP recommends includes to be only used once, so if you can get rid of the usage that would be the best for the code/solution IMHO

**Comment by ed-holland** [comment]
Not a good recommendation as they are includes used in many places to centralize the definition.
Can not get rid of them as we need to be consistent with them

**Comment by ed-holland** [comment]
Problem with dependency check is that it only takes into account objects that have a TADIR entry.
This include does not have a TADIR entry.
Option a) is not possible anymore.

Was there a design decision to limit the deps to TADIR object?

**Comment by larshp** [comment]
I think all includes should have a TADIR entry, if not the system is inconsistent, try tcode `STDR`

**Comment by ed-holland** [comment]
That is a good one... 
Checked, but although it found a lot of missing TADIR, the LFKKAKTIV2CON was not there.

TADIR is related to transporting. I'll go for option b)

Thanks

**Comment by ed-holland** [comment]
FYI: 
There are more than 2000 SAP prog object in our systems that do not have a TADIR entry.
They always have a TRDIR entry.

Because of this, the dependencies are not generated for these includes (and maybe other objects).

closing this issue
