### ISSUE TITLE
sci.abaplint.app name resolution fails

### ISSUE THREAD

**Issue by WegnerDan** [abaplint/abaplint-sci-client#303]
I think this line in the docs might be outdated, because sci.abaplint.app cannot be used due to a DNS failure.

https://github.com/abaplint/abaplint-sci-client/blob/09456b496e2dcb81deba9ffbe60556fc3fb0c778/docs/installation.md?plain=1#L51

**Comment by larshp** [comment]
yea, that is not running anymore

**Comment by WegnerDan** [comment]
other references:

https://github.com/abaplint/abaplint-sci-client/blob/09456b496e2dcb81deba9ffbe60556fc3fb0c778/README.md?plain=1#L11

![image](https://github.com/user-attachments/assets/e6cf7f39-e574-49c3-af75-1f20040132f7)
https://github.com/abaplint/abaplint-sci-client/blob/09456b496e2dcb81deba9ffbe60556fc3fb0c778/src/zabaplint_ui.fugr.lzabaplint_uif01.abap#L681

https://github.com/abaplint/abaplint-sci-client/blob/09456b496e2dcb81deba9ffbe60556fc3fb0c778/src/zabaplint_ui.fugr.xml#L225

Should I patch this out? 

Is there another test server or only the stuff at abaplint.app?

**Comment by larshp** [comment]
> Should I patch this out?

yea, feel free

I'm not really using or building stuff for the SCI integration, I consider it somewhat obsolete
