### ISSUE TITLE
AbapLint Backend not showing version

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint-sci-client#40]
The backend does not show it's abap-lint version in the log or in the SCI results.

Both would be very helpfull with the handling of tickets.

**Comment by larshp** [comment]
agree, suggest that the backend/cloud always returns the abaplint version in the header in all replies

**Comment by larshp** [comment]
yea, so it doesnt show in the SCI results, but quite easy to verify, open the hostname in chrome,

![image](https://user-images.githubusercontent.com/5888506/86017349-3ccedb80-ba24-11ea-9870-898bf8e0aa26.png)

**Comment by ed-holland** [comment]
Running docker, so i exposed port 80 and 443 but this information available.

**Comment by larshp** [comment]
oh, yea, I'm too tired today 😩 it defaults to some port, try port 3000

https://github.com/abaplint/abaplint-cloud-foundry#or-start-in-docker-on-premises
https://github.com/abaplint/abaplint-cloud-foundry/blob/master/src/server.ts#L7

**Comment by ed-holland** [comment]
Also 3000 does not give me any results with Chrome and Edge (forces reroute to https).
Firefox showed it.

**Comment by larshp** [comment]
I still think it should show in abap, but this is an easy workaround for now

**Comment by sbcgua** [comment]
We can add version the the api header. Not that it is a best practice but can be useful indeed and convenient for debugging

**Comment by ed-holland** [comment]
The version beside the sci-variant would surely help. Currently it is very tedious to check if the version in the backend was updated or not creating confusion.

**Comment by larshp** [comment]
output from server: https://github.com/abaplint/abaplint-sci-server/pull/200
