### ISSUE TITLE
Includes not found

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint-sci-client#41]
```
FUGR /REDWOOD/1IDOC > PROG /REDWOOD/L1IDOCTOP [ @4 ] 
Include RSXPGDEF not found, #REDWOOD#1IDOC.FUGR.#REDWOOD#L1IDOCTOP.ABAP

FUGR /REDWOOD/1IDOC > PROG /REDWOOD/L1IDOCTOP [ @5 ] 
Include MBDCONST not found, #REDWOOD#1IDOC.FUGR.#REDWOOD#L1IDOCTOP.ABAP

FUGR /REDWOOD/1IDOC > PROG /REDWOOD/L1IDOCTOP [ @8 ] 
Include <CNTN01> not found, #REDWOOD#1IDOC.FUGR.#REDWOOD#L1IDOCTOP.ABAP

```
![image](https://user-images.githubusercontent.com/53995991/86002563-c8d70800-ba10-11ea-8d39-926e2f46ea02.png)

**Comment by larshp** [comment]
run the new ZABAPLINT_LIST_DEPS report with input `FUGR` `/REDWOOD/1IDOC` and check that the dependency resolution finds the includes

**Comment by mbtools** [comment]
Looks like a SAP bug:
```
REPORT ztest_main.
INCLUDE ztest_include.
INCLUDE <cntn01>.
```
SE38 > Utilities > Environment Analysis finds only the first include.

**Comment by mbtools** [comment]
Not a bug... By design so-called "internal includes" are excluded from the env.analysis (see RS_GET_ALL_INCLUDES). 

You could find those missing includes in WBCROSSI with OTYPE = "IC" and MASTER = "<your prg>" and merge them to the TADIR list in the dependency finder.

**Comment by larshp** [comment]
yea, have to do the lookup in WBCROSSI then

**Comment by ed-holland** [comment]
I've ran the RS_GET_ALL_INCLUDES with RESERVED_INCLUDES
![image](https://user-images.githubusercontent.com/53995991/86440518-dfc87380-bd0a-11ea-869b-bdf2dddca81a.png)
The first one is the Type-pool. The `<CNTN01>` is not showing up.
It is also not showing up in WBCROSSI.

**Comment by ed-holland** [comment]
The extended dependency check finds all includes except the internal. Is the SCI check using a different dependency check?

**Comment by ed-holland** [comment]
what about adding these directly in the abaplint.json (like with macro's etc)?
then they can be added to the dependency list.

**Comment by ed-holland** [comment]
the includes starting with > or < are used for generated reports. The are automatically excluded (among others) from RS_GET_ALL_INCLUDES (which is used to determine the environment).

My proposal is to add some more fields (object + range for name) in ZABAPLINT_DEPENDENCIES that would add these objects to the dependency list. As they then become part of the dependency repository, the include errors should be fixed.

**Comment by larshp** [comment]
yea 👍

**Comment by mbtools** [comment]
+1. Unfortunately some of those includes like the one for icons are full of macros but it should work in most cases

**Comment by ed-holland** [comment]
Verified
