### ISSUE TITLE
Message Classes not found

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint-sci-client#45]
The SAP message classes with strange names `>4` are not recognized although they exist.
![image](https://user-images.githubusercontent.com/53995991/85945182-539a0300-b93c-11ea-99fb-acd6a4d2d9b2.png)
![image](https://user-images.githubusercontent.com/53995991/85945184-55fc5d00-b93c-11ea-9a53-29950b0fa9a6.png)

Also the message class "00" is not.
./src/xbp/#redwood#xbprsdbspva.prog.abap[1, 39]                           - Message invalid: Message class "00" not found (message_exists)
![image](https://user-images.githubusercontent.com/53995991/85945491-64e40f00-b93e-11ea-8079-6db6f35bfaf4.png)

Or should the message classes also be generated as part of the dependencies?

**Comment by larshp** [comment]
issue moved to repo `abaplint/abaplint-abap-backend`

**Comment by larshp** [comment]
have you verified that message class `00` is part of the serialized payload?

**Comment by ed-holland** [comment]
you have to explain that one to me.. still beginner ;-)

**Comment by larshp** [comment]
set a breakpoint at https://github.com/abaplint/abaplint-abap-backend/blob/master/src/deps/zcl_abaplint_deps_find.clas.abap#L285 to make sure it finds that `00` is used in the program

**Comment by ed-holland** [comment]
It never reached the break pint in method list!

**Comment by ed-holland** [comment]
Used 2.38.4

Issue is resolved. Thanks again.
