### ISSUE TITLE
Ignore errors found if Object is SAP delivered

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint-sci-client#47]
When errors are found in a SAP delivered object, then they can not be handled and should be ignored.

SAP Delivered = Source System is SAP.

**Comment by ed-holland** [comment]
This should also be done in AbapLint for the same reason.

**Comment by larshp** [comment]
set the `errorNamespace` = own objects only in the `abaplint.json` config

**Comment by ed-holland** [comment]
that is set to  `"errorNamespace": "^(\/REDWOOD\/)",` or  `"errorNamespace": "^(\/JCS\/)",`

The errors we are getting currently are in 3 area's that are already reported issues:
- structure not found (and dependend errors like "not a structure"
- Message invalid

But we also get these which are clearly outside of the namespace set
![image](https://user-images.githubusercontent.com/53995991/86091001-6f6fe700-baab-11ea-86bc-8075d60cc1f3.png)

**Comment by ed-holland** [comment]
Just came about another exampled. We use the include LBTCHDEF.
It does not adhere to upper/lowercase settings and fails the keyword_case check.

**Comment by ed-holland** [comment]
Or when code is generated. Here an example of generated view include attributes (editor lock and done by SAP*)
![image](https://user-images.githubusercontent.com/53995991/86166597-5439c180-bb15-11ea-8b24-c811193a1853.png)

**Comment by mbtools** [comment]
i exclude such SAP includes/objects:
```
   "keyword_case": {
      "exclude": [
        "<include_name>"
      ],
```
but it would be nice if there was a more general "exclude setting" to avoid processing all rules for SAP objects. Something like
```
{
  "global": {
     "skipSAPobjects":true,
```

**Comment by larshp** [comment]
its 

```
  "syntax": {
    "errorNamespace": "^(Z|Y|LCL_|TY_|LIF_)",
```

**Comment by ed-holland** [comment]
It is not just this check... (there could be more). In my case:
```
FUGR /JCS/BC > PROG LBTCHDEF [ @113 ] 
Indentation problem, expected 0 spaces (indentation)

FUGR /JCS/BC > PROG LBTCHDEF [ @437 ] 
Keyword should be upper case: "type" (keyword_case)

FUGR /JCS/BC > PROG LBTCHDEF [ @113 ] 
Start statement at tab position (start_at_tab)
```

**Comment by larshp** [comment]
in my case, LBTCHDEF gives an error because the SAP standard TADIR entry for the object does not exist,

![image](https://user-images.githubusercontent.com/5888506/86248502-45531d80-bbae-11ea-87e9-6b98801fbb68.png)

![image](https://user-images.githubusercontent.com/5888506/86248509-484e0e00-bbae-11ea-912e-3be5bd5324e9.png)

![image](https://user-images.githubusercontent.com/5888506/86248530-4f751c00-bbae-11ea-991e-5e053a14c9c2.png)

**Comment by ed-holland** [comment]
There is an additional case that causes similar problems.
When one has generated maintenance views, then several of the objects have an editor lock (set by user "SAP*") which can not be changed.

Also here, one gets numerous errors that can not be removed.
` ./src/fpa/#jcs#fpa_actions.fugr.#jcs#lfpa_actionsf00.abap[8, 17]           - Remove space before "," or "." (space_before_dot)
 ./src/fpa/#jcs#fpa_actions.fugr.#jcs#lfpa_actionsf00.abap[8, 9]            - Identifiers should be lower case: "LSVIMFTX" (keyword_case)
 ./src/fpa/#jcs#fpa_actions.fugr.#jcs#lfpa_actionsi00.abap[7, 17]           - Remove space before "," or "." (space_before_dot)
 ./src/fpa/#jcs#fpa_actions.fugr.#jcs#lfpa_actionsi00.abap[7, 9]            - Identifiers should be lower case: "LSVIMITX" (keyword_case)
 ./src/fpa/#jcs#fpa_actions.fugr.#jcs#lfpa_actionst00.abap[10, 1]           - Chain mainly declarations (chain_mainly_declarations)
 ./src/fpa/#jcs#fpa_actions.fugr.#jcs#lfpa_actionst00.abap[13, 26]          - Remove space before "," or "." (space_before_dot)
 ./src/fpa/#jcs#fpa_actions.fugr.#jcs#lfpa_actionst00.abap[14, 25]          - Remove space before "," or "." (space_before_dot)
 ./src/fpa/#jcs#fpa_actions.fugr.#jcs#lfpa_actionst00.abap[17, 19]          - Remove space before "," or "." (space_before_dot)
 ./src/fpa/#jcs#fpa_actions.fugr.#jcs#lfpa_actionst00.abap[17, 3]           - Indentation problem, expected 0 spaces (indentation)
 ./src/fpa/#jcs#fpa_actions.fugr.#jcs#lfpa_actionst00.abap[7, 17]           - Identifiers should be lower case: "STATUS_/JCS/FPA_ACTIONS" (keyword_case)
`

**Comment by ed-holland** [comment]
Now with a great effort from @larshp (many Thanks), most of the issues with syntax are resolved.

What now is left are +200 errors related to rules being applied to generated code or sap original code.
I do not wish to water down the rules more to keep the quality of our code up.

![image](https://user-images.githubusercontent.com/53995991/89759082-aa712b80-dae9-11ea-946f-7bf7ab4f236b.png)

**Comment by larshp** [comment]
yes, if the INLCUDE is a dependency, and used in a main object, then the errors should be ignored

**Comment by mbtools** [comment]
It’s pointless to check any SAP code. Just scan to find dependencies. But check the include if it is used in the repo code.

**Comment by ed-holland** [comment]
By squashing the FORMS and Functions in the dependency repository, the issue is resolved.
