### ISSUE TITLE
AbapLint Backend fails his own checks

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint-sci-client#48]
![image](https://user-images.githubusercontent.com/53995991/86050698-80413e00-ba54-11ea-978c-a342374611ec.png)

There are more than 16 pages of errors.

**Comment by larshp** [comment]
in https://github.com/abaplint/abaplint-abap-backend/pull/49#issuecomment-651570060 it reports unused_variables but not on command line, this is within the same class

unknowns: what is the max dependency depth configured in your system?

**Comment by ed-holland** [comment]
It is not defined. But also with level 2 (which takes ages) there still are problems.
Are you not having this issue?

**Comment by ed-holland** [comment]
I've reran SCI on the package as there where many changes made to Linter/Dependencies (Thanks @larshp). 
SCI lint configuration was updated from AG and saved.
![image](https://user-images.githubusercontent.com/53995991/88153111-43a4d480-cc05-11ea-9544-c7246fd2bd70.png)

When running AbapLint on the repository, no issues are found.

abaplint-backend from 2020-07-19 13:25:38
abaplint version: 2.38.1

**Comment by ed-holland** [comment]
I've rechecked with the latest Lint version 2.39.21 and abaplint.json. The list has changed but there are still differences.

![image](https://user-images.githubusercontent.com/53995991/91529044-e0dfe080-e908-11ea-9d6f-aaef83924469.png)

Running Linter externally, has no issues.
![image](https://user-images.githubusercontent.com/53995991/91529135-0ff65200-e909-11ea-928f-0da57e809996.png)

**Comment by ed-holland** [comment]
With the latest AbapLint 2.48.0, the differences between SCI and abaplint are reduced.
![image](https://user-images.githubusercontent.com/53995991/93742896-3731fd80-fbef-11ea-9ff2-94e5ecf25837.png)

**Comment by ed-holland** [comment]
Closing this one. Not so important.
