### ISSUE TITLE
Ability to run Code Inspector on a subpackage

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint-sci-client#52]
Running Code-Inspector can take quite some time.
To make it easier, the packages are structured hierarchically. One can use the folder view to reduce the list of objects.

It would be a great improvement if only the current package (and its sub packages) would be checked by Code-Inspector.

**Comment by larshp** [comment]
in SAP standard SCI you can make an object set containing only specific packages

**Comment by ed-holland** [comment]
That would mean that variants need to be created for each package and the default removed from the settings.
The list with standard variants is very long. This would be sub optimal.

**Comment by larshp** [comment]
could write a small utility program to run a variant on a subpackage, but I think its outside scope of this project

most of the code needed can be copied from https://github.com/larshp/abapGit/blob/master/src/zcl_abapgit_code_inspector.clas.abap

**Comment by ed-holland** [comment]
An acceptable solution i think. It speeds up the checks.
If there where actions on folders, then it could be tied to this utility.

**Comment by ed-holland** [comment]
It would also be of help to run it over a Transport Request.

**Comment by ed-holland** [comment]
possible using ZABAPLINT_RUN_SCI provided by #173
