### ISSUE TITLE
Path removed from Message from Code-Inspector. Was getting to long cutting of important information 

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint-sci-client#56]
Extracted from #42.

The error description was getting to long. If the information is still required, how should it be made visible?

Old:
![image](https://user-images.githubusercontent.com/53995991/86152384-60ffea80-bb00-11ea-8aaf-a15ce76d85c8.png)
New:
![image](https://user-images.githubusercontent.com/53995991/86217485-d65ed000-bb7f-11ea-80eb-41092d1a3c64.png)

Options for resolution:
- [ ] remove the file path (current implementation)
- [ ] put it at the end
- [ ] on a new line?
- [ ] as hover-text over the url
- [ ] only show it when required

**Comment by larshp** [comment]
where is the screenshot from? I'm guessing abapGit, it gets the data from Code Inspector, we cannot add additional functionality to code inspector

**Comment by ed-holland** [comment]
The screenshot is from AbapGit after executing SCI. 
Is the result from SCI just shown or are we looping over the messages and present them?

The question is more, if there is a need for the path information?

**Comment by larshp** [comment]
see https://github.com/larshp/abapGit/blob/420e6f59649766bc72c9c9422dd08def637196ee/src/ui/zcl_abapgit_gui_page_codi_base.clas.abap#L151

Code inspector does not have the concept of files, only objects and messages

**Comment by ed-holland** [comment]
As we are rendering the url, is it not possible to add a hover text or just add the path as part of the url description?

**Comment by larshp** [comment]
The output structure from code inspector is the following, which can be presented in any way, in abapGit,

![image](https://user-images.githubusercontent.com/5888506/86246810-e68ca480-bbab-11ea-860c-f08d8dc9ee92.png)

**Comment by ed-holland** [comment]
Working as expected. Thanks
