### ISSUE TITLE
when serializing dependencies, make sure it takes only the master language

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint-sci-client#59]
this should kick in,
https://github.com/larshp/abapGit/blob/master/src/objects/zcl_abapgit_object_msag.clas.abap#L222

**Comment by larshp** [comment]
tested, it currently takes all languages

**Comment by ed-holland** [comment]
Check the xml file of a MSAG. It is only generating the Master Language for the messages.
What makes the fill big, is the dependent long Text.
![image](https://user-images.githubusercontent.com/53995991/87224678-94a40580-c387-11ea-9355-b910673ca02a.png)

For MSAG's outside of our development package, the long texts should not be downloaded.
If it is our development package, it should only do the requested language (if setting say so).

**Comment by ed-holland** [comment]
There is more that is not needed for dependencies.
![image](https://user-images.githubusercontent.com/53995991/87225565-5c53f580-c38e-11ea-9ced-d52674dc96d9.png)

**Comment by larshp** [comment]
for longtexts, see https://github.com/abaplint/abaplint-sci-client/issues/75 and need https://github.com/larshp/abapGit/pull/3607 to be merged
