### ISSUE TITLE
Dependencies generated can not be pulled due to name

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint-sci-client#65]
The dependencies generated contain message area's named `>0` etc. 
![image](https://user-images.githubusercontent.com/53995991/86534401-8150f000-bed8-11ea-95d7-6c0edc706dad.png)

The two function modules at the end are:
`AA_DEP_KEY_IS_UOP?`
`AA_DEPR_KEY_IS_UOP?`

The include a question mark in the name.

**Comment by larshp** [comment]
heh, hmm, git is okay with the filenames, but windows is limited, not sure about linux,

![image](https://user-images.githubusercontent.com/5888506/86535204-ec052a00-bede-11ea-961c-cd25514cf64b.png)

**Comment by larshp** [comment]
guessing this will be solved by https://github.com/larshp/abapGit/pull/3564

**Comment by ed-holland** [comment]
verified issue is fixed.

**Comment by ed-holland** [comment]
Need to reopen. Issue is still there.

**Comment by ed-holland** [comment]
This also blocks VisualCode extension AbapLint from retrieving the dependencies.

![image](https://user-images.githubusercontent.com/53995991/91697640-c197bc00-eb71-11ea-8b57-87d3fb231522.png)

**Comment by larshp** [comment]
ref https://github.com/larshp/abapGit/issues/3817

**Comment by ed-holland** [comment]
All dependency files now can be cloned on Windows.

Issue resolved. Thanks
