### ISSUE TITLE
serializer does not use package for path

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint-sci-client#69]
In the AbapLint Backend, the serializer is called to generate dependency code.
![image](https://user-images.githubusercontent.com/53995991/86953213-668aaf80-c154-11ea-83bd-e00c193b77dd.png)
The package is filled
![image](https://user-images.githubusercontent.com/53995991/86953319-8e7a1300-c154-11ea-8ca3-c9ef91203e98.png)
The resulting path does not contain it.
![image](https://user-images.githubusercontent.com/53995991/86953405-b1a4c280-c154-11ea-9c47-343aca6e70e4.png)

Is that meant to be this way?

**Comment by ed-holland** [comment]
Looks like the problem is here:
![image](https://user-images.githubusercontent.com/53995991/86966972-40700a00-c16a-11ea-80f9-413a5c8f5105.png)

**Comment by larshp** [comment]
suggest using the package name for path, so object A in package B will be `/src/b/a.obj.xml`

and ignore the nesting of packages
