### ISSUE TITLE
Rename repos ?

### ISSUE THREAD

**Issue by sbcgua** [abaplint/abaplint-sci-client#71]
What about renaming these 2 repos: the names are rather confusing currently and do not show the link between each other. e.g. `...backend` is in fact a client application.

what about: 
- `abaplint-sci-client` for this one
- and `abaplint-sci-server` or `abaplint-sci-backend` for the js server or just `abaplint-backend` (which will follow the docker hub name)

**Comment by larshp** [comment]
done

https://github.com/abaplint/abaplint-sci-client

https://github.com/abaplint/abaplint-sci-server

**Comment by sbcgua** [comment]
🎉 Thanks

**Comment by larshp** [comment]
I didnt rename stuff/links
