### ISSUE TITLE
events missing as dependencies?

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint-sci-client#84]
example with abapGit, following should be found as a dependency chain,

zcl_abapgit_popups -> cl_salv_events_table -> if_salv_events_actions_table

**Comment by larshp** [comment]
probably related to the "continue into SAP objects" feature, need https://github.com/abaplint/abaplint-sci-client/issues/133 first

**Comment by mbtools** [comment]
Run `ZABAPLINT_LIST_DEPS` for `ZCL_ABAPGIT_POPUPS`:
```
CLAS CL_SALV_EVENTS_TABLE                     SALV_OM_METADATA
INTF IF_SALV_EVENTS_ACTIONS_TABLE             SALV_OM_OBJECTS
```
can be closed
