### ISSUE TITLE
ZCL_ABAPLINT_DEPS_SERIALIZER->SERIALIZE and zcl_abapgit_injector

### ISSUE THREAD

**Issue by sbcgua** [abaplint/abaplint-sci-client#85]
The reference to a test class (identification with FOR TESTING) is only possible in test classes.

![image](https://user-images.githubusercontent.com/15635498/87255059-1f702780-c490-11ea-910e-cae9b8b3811d.png)

for `zcl_abapgit_injector=>set_longtexts( lo_longtexts ).`

**Comment by larshp** [comment]
update to latest abapGit, https://github.com/larshp/abapGit/pull/3614

**Comment by sbcgua** [comment]
yeap, gone. Thanks !
