### ISSUE TITLE
ASSERT Exception in encode_tree: Empty name name 

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint-sci-client#89]
Running ZABAPLINT_DEPENDENCIES assert exception was raised due to an empty name in the node table
![image](https://user-images.githubusercontent.com/53995991/87256950-39613880-c497-11ea-85ce-f5b712333ff0.png)
Node table
![image](https://user-images.githubusercontent.com/53995991/87256943-2cdce000-c497-11ea-88e1-7353ff3f65b7.png)

**Comment by larshp** [comment]
guess its something with an empty package, the nodes equals folders which equals packages in this case

**Comment by ed-holland** [comment]
Issue is due to object type determination if not correct. Enhancing senvi conversion.

**Comment by ed-holland** [comment]
Found FUGR without package (example /1BCDWBEN/SEN0). Is that a problem.
Object has no TADIR entry (function group and main program).

**Comment by larshp** [comment]
suggest skipping objects that are inconsistent

alternatively default the package name to "dummy" or something

**Comment by ed-holland** [comment]
the object is consistent. It is a generated enqueue fugr.

Some objects like PARA do not have to exist. This is perfectly valid (for SAP). 
What to do about them?

**Comment by ed-holland** [comment]
Even with all object having packages specified, the error still occurs.
Using ZABAPLINT_LIST_DEPS is was possible to serialize and download the same package!

**Comment by ed-holland** [comment]
issue was caused by namespaces in the path. Fixed with #92

**Comment by ed-holland** [comment]
Verfied.
